# server
server:
  port: 9002

# spring
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  # thymeleaf
  thymeleaf:
      encoding: UTF-8
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      servlet:
        content-type: text/html; charset=utf-8

logging:
  path: logs
  level:
    root: ERROR
