# server
server:
  port: 9002
  
# spring
spring:
  # thymeleaf
  thymeleaf:
      encoding: UTF-8
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      servlet:
        content-type: text/html; charset=utf-8
