# server
server:
  port: 9001

spring:
  application:
    name: project-provider
  # DataSource Config
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml