# server
server:
  port: 9001

spring:
  application:
    name: project-provider
  profiles:
    active: home
  

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level: 
    root: INFO
    
---
# at home environment
spring:
  profiles: home
  # DataSource Config
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

---
# at company environment
spring:
  profiles: home
  # DataSource Config
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver